PolyMathOrg/PolyMath

- src/.properties
- src/BaselineOfPolyMath/BaselineOfPolyMath.class.st
- src/BaselineOfPolyMath/package.st
Convert configuration to baseline.
Fixes https://github.com/PolyMathOrg/PolyMath/issues/46
> Convert Configuration to Baseline

- src/Math-Core/ArrayedCollection.extension.st
- src/Math-Core/PMVector.class.st
- src/Math-Tests-DHB-Numerical/PMVectorTest.class.st
@olekscode do a commit on master instead of devlopement. This PR is to sync devlopment branch with master.
> Sync dev with master

- src/BaselineOfPolyMath/BaselineOfPolyMath.class.st
- src/Math-Permutation/ManifestMathPermutation.class.st
- src/Math-Permutation/PMPermutation.class.st
- src/Math-Permutation/PMPermutationTest.class.st
- src/Math-Permutation/package.st
is this the way one does these things???
werner
> added permutation package & changed baseline accordingly

- src/Math-Tests-AutomaticDifferenciation/DualNumberTest.class.st
> DualNumberTest>>testRaisedTo made compatible with pharo7

- src/Math-Tests-Matrix/PMMatrixTest.class.st
This addresses issue https://github.com/PolyMathOrg/PolyMath/issues/84
> [Issue 84] Bug Fix - PMMatrix Does Not Respond To The Assert Message

- src/Math-Tests-Random/PMBinomialGeneratorTest.class.st
@SergeStinckwich Here, to achieve the certainty we need, I set the seed to zero and removed the square root, but to be honest doing TDD on Random behaviour/phenomena is a weak point of mine so I'd appreciate some advice on how best to proceed. I'm not sure why we're testing that the floor and ceilings of the numbers generated are within 20% of the mean. To be precise I don't know how we came up with the 20%. I'd like to extract it to an intention revealing temp variable but I don't know what it represents.
> [issue-104] Some tests methods fail randomly Part 1: BinomialGenerator Tests

- src/Math-Core/PMVector.class.st
- src/Math-Core/PMWeightedPoint.class.st
> Removed PMVector sum for speedup

- src/Math-Random/PMBinomialGenerator.class.st
- src/Math-Random/PMExponentialGenerator.class.st
- src/Math-Random/PMPoissonGenerator.class.st
- src/Math-Tests-Random/PMBinomialGeneratorTest.class.st
- src/Math-Tests-Random/PMExponentialGeneratorTest.class.st
- src/Math-Tests-Random/PMGaussianGeneratorTest.class.st
- src/Math-Tests-Random/PMPoissonGeneratorTest.class.st
- src/Math-Tests-Random/PMRandomSample.class.st
- src/Math-Tests-Random/SampleNumericalData.class.st
Issue: #105 
This PR continues refactoring the tests package. Here I have tried to use what I believe is the correct domain language so that the tests serve as documentation. However, this area of Mathematics is not my strong point so it'd be great to get some suggestions from fellow maintainers of method names, specifically whether we should use the word 'mean' or 'expected value'.
> [Issue 105] Refactor Math-Random Tests Package

- .smalltalk.ston
- README.md
**Issue:** #106 
This PR:
- corrects the coveralls badge which was pointing to a temporary issue branch;
- begins coverage of the `Math-FunctionFit` package.
> [issue-106] Support For coveralls.io

- src/Math-AutomaticDifferenciation/Number.extension.st
- src/Math-AutomaticDifferenciation/PMDualNumber.class.st
- src/Math-AutomaticDifferenciation/PMGradient.class.st
- src/Math-AutomaticDifferenciation/PMHyperDualNumber.class.st
- src/Math-Complex/PMComplex.class.st
- src/Math-Complex/PMComplex.extension.st
- src/Math-Tests-AutomaticDifferenciation/PMDualNumberTest.class.st
- src/Math-Tests-AutomaticDifferenciation/PMGradientAndHessianTest.class.st
- src/Math-Tests-AutomaticDifferenciation/PMHyperDualNumberTest.class.st
> Use double dispatch for PMDualNumber

- src/ExtendedNumberParser/ExtendedNumberParser.class.st
- src/Math-FunctionFit/PMAnotherGeneticOptimizer.class.st
- src/Math-ODE/PMButcherTableauStepper.class.st
- src/Math-ODE/PMStepper.class.st
- src/Math-TSNE/PMTSNE.class.st
- src/Math-Tests-Accuracy/PMAccuracyTestExample.class.st
- src/Math-Tests-KDTree/PMKDTreeTest.class.st
Various issues with loading into PharoGs. One issue is using an instance variable name as a method argument or method temp. Another is spacing where a dot comes between two names; GemStone treats this as a special syntax for direct instance variable access (eek!).
> Cleanup to load in PharoGs

- src/Math-Accuracy-Core/PMAccuracy.class.st
- src/Math-Tests-PrincipalComponentAnalysis/PMStandardizationScalerTest.class.st
> Fix some of the red tests for Pharo 8

- src/Math-Numerical/PMHillClimbingOptimizer.class.st
Add start to wrote class comment for this class.
Clean the code
> Add one example of use of PMHillClimbingOptimizer

- src/BaselineOfPolyMath/BaselineOfPolyMath.class.st
- src/Math-Complex/Number.extension.st
- src/Math-Complex/Object.extension.st
- src/Math-Complex/PMComplex.class.st
- src/Math-Complex/PMComplex.extension.st
- src/Math-Core-Distribution/PMMultivariateNormalDistribution.class.st
- src/Math-Core-Distribution/PMNormalDistribution.class.st
- src/Math-Core/PMVector.class.st
- src/Math-Matrix/PMMatrix.class.st
- src/Math-Matrix/PMSymmetricMatrix.class.st
- src/Math-Tests-Complex/PMComplexTest.class.st
- src/Math-Tests-Core-Distribution/PMMultivariateNormalDistributionTest.class.st
- src/Math-Tests-Core-Distribution/package.st
- src/Math-Tests-Core/PMVectorTest.class.st
- src/Math-Tests-Matrix/PMMatrixTest.class.st
This pull request includes the following contributions:
```Smalltalk
5 isRealNumber.  "true"
(5 + 2i) isRealNumber. "false"
```
```Smalltalk
5 isComplexConjugateOf: 5. "true"
(5 + 2i) isComplexConjugateOf: (5 - 2i). "true"
5 isComplexConjugateOf: (5 + 0i). "true"
```
Answer true if and only if all values of vector or matrix are real numbers
```Smalltalk
a := #(1 4 -2 0.5) asPMVector.
b := { 1 . 4 . -2 . 0.5 + 3i } asPMVector.
a isReal. "true"
b isReal. "false"
```
```Smalltalk
a := PMMatrix rows: #( 
(1 3 0)
(1 2 -4)
(-8 5 -1)).
b := PMMatrix rows: { 
{ 1 . 3 + 4i . 0 } .
{ 1 - 2i . 2 . -4 } .
{ -8 + 0i . 5 . -1 } }.
a isReal. "true"
b isReal. "false"
```
The matrix is:
- **Hermitian** if it is square and the element in the i-th row and j-th column is equal to the complex conjugate of the …
> Implemented Cholesky Decomposition and the Multivariate Normal Distribution

- src/Math-Matrix/PMSingularValueDecomposition.class.st
Remove instance variables not used and also transform iv as temporary variables in SVD
> Clean variables in SVD

- src/Math-Matrix/PMNDArray.class.st
- src/Math-Matrix/PMNDArrayTest.class.st
- src/Math-Matrix/ShapeMismatch.class.st
It contains :
- A method allowing to check that the matrices which one wishes to multiply have the same shape.
- A method to calculate the Hadamard product
- And test methods for this Hadamard product
> Addition of matrix product

- src/Math-Core/PMVector.class.st
- src/Math-KolmogorovSmirnov/PMKolmogorovSmirnov2Sample.class.st
- src/Math-Matrix/PMMatrix.class.st
> Replaced take: calls with numberOfCombinationsTaken:

- src/Math-Matrix/PMSingularValueDecomposition.class.st
Renamed instance variables with more descriptive names.
> Fixes #236

- src/Math-Tests-Matrix/PMMatrixTest.class.st
- src/Math-Tests-Numerical/PMNumericalMethodsTestCase.class.st
Fixed #263 
Removed dependency on Math-Polynomial and Math-Numerical from Math-Tests-Matrix.
Also improved some tests by splitting them into smaller ones and improving the code
> Improved several test cases to reduce coupling and make the code cleaner

- src/Math-Tests-Complex/PMComplexTest.class.st
- Introduced classification that mirrors production
- classified some test methods according to the classification of the messages they exercise
- improved the named of some test messages.
> Refactor complex number tests

- src/Math-Quaternion/PMQuaternion.class.st
- src/Math-Tests-Quaternion/PMQuaternionTest.class.st
Make the test for the Natural Log of Quaternion message.
> Refactor Quaternion Natural Log

- src/Math-Quaternion/Number.extension.st
- src/Math-Quaternion/PMComplexNumber.extension.st
- src/Math-Quaternion/PMPolynomial.extension.st
- src/Math-Quaternion/PMQuaternion.class.st
- src/Math-Quaternion/PMVector.extension.st
- src/Math-Tests-Quaternion/PMQuaternionTest.class.st
- Improve the multiplication tests to inspire confidence when refactoring the method of the `*` message.
- Replaced type checking with Double Dispatch.
> Refactor: Quaternion multiplication

- src/Math-Matrix/PMMatrix.class.st
- src/Math-Matrix/PMQRDecomposition.class.st
- src/Math-Tests-Matrix/PMQRTest.class.st
This is to apply the Replace Method With Method Object Refactoring as a starting point.
QR Decomposition is an operation that mathematicians refer to, so it Is worth making explicit in the form of a class
> Refactor: Extract QR Decomposition Class
