- src/Math-Matrix/PMMatrix.class.st
- src/Math-Tests-Matrix/PMMatrixTest.class.st
#atAllPut: (Matrix instance protocol)
#atColumn:put: repeat:
#initializeRows:columns:
#rows:columns: (Matrix class protocol)
#rows:columns:element: (Matrix class protocol)
> Added convenience PMMatrix methods with tests

- src/Math-Tests-KernelSmoothing/PMSmoothedDensityTest.class.st
- src/Math-Tests-KernelSmoothing/package.st
- src/Math-Tests-Number-Extensions/NumberExtensionsTest.class.st
- src/Math-Tests-Number-Extensions/package.st
- src/Math-Tests-PrincipalComponentAnalysis/PMPrincipalComponentAnalyserTest.class.st
- src/Math-Tests-PrincipalComponentAnalysis/PMStandardizationScalerTest.class.st
- src/Math-Tests-PrincipalComponentAnalysis/package.st
- src/Math-Tests-RandomDistributionBased/PMLaplaceGeneratorTest.class.st
- src/Math-Tests-RandomDistributionBased/package.st
Moved the test classes to more sensible packages, named in accordance with the existing convention, see [issue 21](https://github.com/PolyMathOrg/PolyMath/issues/21)
As a check, I ran each test and made sure it was green. Two tests were found to be failing and have been identified [here](https://groups.google.com/forum/#!topic/polymath-project/IzdF072lpoY).
> [Issue 21] All the tests classes should be labelled correctly

- src/Math-Tests-Permutation/PMPermutationTest.class.st
- src/Math-Tests-Permutation/package.st
- src/Math-Tests-TSNE/TSNETest.class.st
- src/Math-Tests-TSNE/package.st
This addresses issue 85, where some other `TestCase` classes were found to be in production packages.
As a check, after moving the `TestCase` classes, I ran them in their new packages and they were all green.
> [issue-85] All Test Classes Should Be Labelled Correctly (Part 2)

- src/Math-Tests-PrincipalComponentAnalysis/PMPrincipalComponentAnalyserTest.class.st
This address issue #88, where `pca2` was the SVD-based implementation whereas it should be the Jacobi Transformation. 
After making the change the test continued to pass.
> [issue-88] Corrected the type.

- src/Math-Core/PMVector.class.st
- src/Math-PrincipalComponentAnalysis/PMPrincipalComponentAnalyserSVD.class.st
- src/Math-PrincipalComponentAnalysis/SciKitLearnEigenvectorFlipAlgorithm.class.st
- src/Math-Tests-DHB-Numerical/PMVectorTest.class.st
- src/Math-Tests-Matrix/PMJacobiTransformationTest.class.st
- src/Math-Tests-PrincipalComponentAnalysis/SciKitLearnEigenvectorFlipAlgorithmTest.class.st
This PR has got the scikit-learn based sign flipping algorithm working. We started by extracting a class that, given U and V, performs the sign flipping. As an acceptance test, we used the U and V matrices computed by scikit-learn. 
In the course of this work we found that for the SVD-based implementation of PCA, the V matrix in PolyMath does not match scikit learn's in terms of the signs; the magnitudes of the elements match though (see comments in #81). As a cross-check we used Wolfram Alpha to perform the same decomposition. Interestingly that does match the matrix yielded by PolyMath. We also checked that 
V<sup>-1</sup>M<sup>T</sup>MV 
yields a diagonalised matrix, which it did.
> [Issue 81] 2 PCA implementations that give same results but different from Python scikit-learn implementation

- src/Math-PrincipalComponentAnalysis/PMPrincipalComponentAnalyserSVD.class.st
- src/Math-PrincipalComponentAnalysis/PMSciKitLearnSVDFlipAlgorithm.class.st
- src/Math-Tests-PrincipalComponentAnalysis/PMSciKitLearnSVDFlipAlgorithmTest.class.st
Classes in PolyMath should be prefixed with `PM`. This PR contains the change for this. Along the way I improved the name of the class a bit.
> [issue-81] Name of the class now conforms to the PolyMath codestyle.

- src/Math-Core/PMVector.class.st
- src/Math-Tests-PrincipalComponentAnalysis/PMPrincipalComponentAnalyserTest.class.st
- src/Math-Tests-PrincipalComponentAnalysis/PMSciKitLearnSVDFlipAlgorithmTest.class.st
- src/Math-Tests-PrincipalComponentAnalysis/PMScikitLearnSVDFlipAlgorithmSandiaTest.class.st
This PR relates issue #81 
I used Scikit-Learn to decompose a matrix from a [Sandia National Lab paper](https://www.researchgate.net/publication/227677444_Resolving_the_sign_ambiguity_in_the_singular_value_decomposition) on SVD sign ambiguity. The U and V from this computation were used as 'triangulation' tests.
I mobbed with @olekscode and @SergeStinckwich and we decided that for the PCA tests we could check that the moduli of the matrix elements were close enough.
> [Issue 81] - 2 PCA implementations that give same results but different from Python scikit-learn implementation

- src/Math-Core/PMVector.class.st
The == operator should not be overridden. Removed that block entirely due to it having no real application.
Fixes issue #90.
> Removed == method from PMVector

- src/Math-Core/PMVector.class.st
- src/Math-Core/PMWeightedPoint.class.st
- src/Math-Matrix/PMJacobiTransformationHelper.class.st
- src/Math-Matrix/PMLUPDecomposition.class.st
- src/Math-Matrix/PMLargestEigenValueFinder.class.st
- src/Math-Matrix/PMLinearEquationSystem.class.st
- src/Math-Matrix/PMMatrix.class.st
- src/Math-Matrix/PMSingularMatrixError.class.st
- src/Math-Matrix/PMSingularValueDecomposition.class.st
- src/Math-Matrix/PMSymmetricMatrix.class.st
- src/Math-PrincipalComponentAnalysis/PMSciKitLearnSVDFlipAlgorithm.class.st
- src/Math-Tests-Core/PMVectorTest.class.st
- src/Math-Tests-Matrix/PMAdditionalTest.class.st
- src/Math-Tests-Matrix/PMMatrixTest.class.st
- src/Math-Tests-Matrix/PMQRTest.class.st
- src/Math-Tests-Matrix/PMRestTest.class.st
- src/Math-Tests-Matrix/PMSingularValueDecompositionTest.class.st
- src/Math-Tests-Matrix/PMSymmetricMatrixTest.class.st
Issue: #29 
I looked at the wiki and found that [Hadamard product](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)) is the name given to this binary operation. It is also known as the Schur product, however Serge and I agreed on `hadamardProduct:` as the name we might give the message.
Discussion around this issue raised a concern about silent breaks so I have introduced (added) the new `hadardProduct:` and marked `dot:` as deprecated. We can then defer when we want to remove the method completely.
I checked for usages and I have replaced calls to `dot:` everywhere except its use in the t-NSE package as @AtharvaKhare is currently doing some work there.
> Issue 29 - PMVector/PMMatrix >> #dot: does not compute a dot product.

- src/Math-TSNE/PMTSNE.class.st
- src/Math-Tests-TSNE/PMTSNETest.class.st
> Implementing the t-SNE algorithm

- src/Math-Core/PMVector.class.st
- src/Math-Core/PMWeightedPoint.class.st
- src/Math-Matrix/PMMatrix.class.st
- src/Math-Tests-Core/PMVectorTest.class.st
- src/Math-Tests-Matrix/PMMatrixTest.class.st
Issue: #29
After introducing the correct name for the operation (Schur product/elementwise product are also options) I replaced all calls to the deprecated `dot:` with `hadamardProduct:` and finally removed the message completely.
We are happy to do this now as we have not released v1.0 yet.
> [Issue 29] PMVector/PMMatrix >> #dot: does not compute a dot product.

- src/Math-PrincipalComponentAnalysis/PMStandardizationScaler.class.st
- src/Math-Tests-PrincipalComponentAnalysis/PMStandardizationScalerTest.class.st
This happened when one of the input features was constant.
- Set scale to 1 for the feature which is constant
- Added two tests for this case
Fixes #124.
> Fixed ZeroDivideError in PMStandardizationScaler

- src/Math-TSNE/PMTSNE.class.st
New methods `step` and `postStep` have been added.
`postStep` will contain all viz and debug methods.
A new `stateVariables` contains required variables for
the steps.
> Refactored PMTSNE to include steps

- src/Math-Random/PMBinomialGenerator.class.st
- src/Math-Random/PMLehmerRandomGenerator.class.st
- src/Math-Random/PMLinearCongruentialRandomGenerator.class.st
- src/Math-Random/PMMarsagliaKissRandomGenerator.class.st
- src/Math-Random/PMMersenneTwisterRandomGenerator.class.st
- src/Math-Random/PMParkMillerMinimumRandomGenerator.class.st
- src/Math-Random/PMPseudoRandomNumberGenerator.class.st
- src/Math-Tests-Random/PMBernoulliGeneratorTest.class.st
- src/Math-Tests-Random/PMBinomialGeneratorTest.class.st
- src/Math-Tests-Random/PMExponentialGeneratorTest.class.st
- src/Math-Tests-Random/PMLaplaceGeneratorTest.class.st
- src/Math-Tests-Random/PMLehmerRandomTest.class.st
- src/Math-Tests-Random/PMLinearCongruentialRandomTest.class.st
- src/Math-Tests-Random/PMNumberGeneratorTest.class.st
- src/Math-Tests-Random/PMPoissonGeneratorTest.class.st
- src/Math-Tests-Random/PMPseudoRandomNumberGeneratorTest.class.st
Issue: #105 
I have improved the tests a bit to make them read more as documentation and improved class naming. There is more refactoring to do, so I am submitting this PR as part 1.
> [Issue 105] Math-Random Package Is Messy - Improve Naming, Refactor Tests

- src/Math-TSNE/PMTSNE.class.st
- Renamed variable `computeErrorEvery` to `updateErrorEvery`
- Added `updateError` variable which calculates error only when true
- Added grid vizualization example
- Added linked-rings vizualization and generator
> Added vizualization examples for PMTSNE

- src/Math-Random/PMLinearCongruentialRandomGenerator.class.st
- src/Math-Random/PMMersenneTwisterRandomGenerator.class.st
- src/Math-Random/PMParkMillerMinimumRandomGenerator.class.st
Issue: #105 
This PR looks at:
- reducing the long method smell in the `PMMersenneTwisterRandomGenerator` class' `nextInteger` method. Here I extracted the block of code that performs 'tempering' to an intention-revealing method, using [the original paper](http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/ARTICLES/mt.pdf) for guidance on naming. No new tests were written as this is the tiniest refactor I could perform given the lack of knowledge I have in this area. I used defect injection to check the existing tests gave me sufficient covering;
- correcting the Parker-Miller and Congruential class' method categorisations so that they match the super class's.
A future PR will look at adding more tests to increase confidence in refactoring.
> [Issue 105] Math-Random package is messy

- .smalltalk.ston
- README.md
Issue: #106
I have added test coverage tool coveralls.io and discovered along the way that some packages cause the SmallTalkCI to fail, including: 
- Math-FFT and Math-FunctionFit;
- Math-ODE
- Math-Accuracy
I would like to address these in the next PR. This one gets a slice out the door so that we can observe the current landscape and the confidence we may have in refactoring code.
> [Issue 106] Support For coveralls.io

- src/Math-Accuracy-Core/PMAccuracy.class.st
- src/Math-Tests-Accuracy/PMAccuracyTest.class.st
- src/Math-Tests-Accuracy/PMAccuracyTestExample.class.st
Issue: #106 
The `Math-Accuracy` package causes breakages in the coverage part of smalltalkCI. Debugging the root cause is hard because the package itself is a little hard to follow. This refactor, the first of many, aims to make the package much easier to understand.
The automated tests seem to very effective at catching bugs as one particular refactor I performed caused tests to fail.
Having refactored `findKey` we discovered that if a key is not found, an error is raised. I appealed to @WernerK via the mailing list and he suggested remove the error raising code entirely if it was causing problems. In this PR, then, I decided to return an empty string to keep the interface post-condition consistent, in that it will always return a string.
> [Issue 106] Refactor Math-Accuracy

- .smalltalk.ston
Issue #106 
Here I have got the `Math-ODE` package covered by coverall.io. I tried to list 'Math-O*' originally but some travis jobs failed, running out of memory, so as a small step forward I have hard-coded the package name until we can find a better way forward.
> [Issue 106] Get Math-ODE Covered By Coveralls.io 

- src/BaselineOfPolyMath/BaselineOfPolyMath.class.st
This commit should fix the compilation errors in PharoGs that were reported for SMark.
> Updated SMark version to 1.0.3

- src/Math-Tests-Accuracy/PMAccuracyTestExample.class.st
Issue: #152 
This PR removed some magic from initialising key-value pairs as it was causing [travis to fail](https://travis-ci.org/PolyMathOrg/PolyMath/builds/572469507) when the package test coverage was analysed by coveralls.io.
To confirm that my refactors were safe to do, I injected defects into the work to make sure that tests were failing.
> [Issue 152] Remove Magic From 'initialize' Methods

- src/Math-Tests-Accuracy/PMAccuracyFindKeyTest.class.st
- src/Math-Tests-Accuracy/PMAccuracyTestExample.class.st
I discovered while working on #154 that the `testArgumentAt:` test was [still failing](https://travis-ci.org/PolyMathOrg/PolyMath/builds/582400649). I carried out a quick spike to see if setting `matchingMessage` to `'AllTheRest'` when the property is not `'initialize'` or a property with a corresponding `'initialize<Property>'` message fixes it, [and it does](https://travis-ci.org/PolyMathOrg/PolyMath/jobs/582403224).
To mitigate risk at this stage, I corrected `findKey` by correcting the behaviour in the subclass defined in the test package (`PMAccuracyTestExample`). I began by extracting some of the code to a more testable method, `findKey:` and using that in the said overriding message. Regression tests were written for the newly extracted method to ensure no new bugs were introduced: …
> [issue-154] Corrected the behaviour of findKey to return 'AllTheRest' when selector has no corresponding initialize message.

- src/Math-Tests-Accuracy/PMAccuracyTest.class.st
- src/Math-Tests-Accuracy/PMDataTreeTest.class.st
Issue #154 is proving a little difficult to fix. Therefore I have begun a targeted refactor of the production and test code to help a future developer understand what the Accuracy package does easily.
This PR breaks up the `testDataTree` code into smaller (hopefully easier to understand) blocks of code.
What is interesting here is that the `run` message is the generator of the dataTree object. It feels that that is what we are really testing.
The reason I chose to work on the `testDataTree` message first is that from my earlier spike, I discovered that part of that method fails when I try to get the Accuracy package covered by coveralls.io in the [usual way](https://github.com/PolyMathOrg/PolyMath/pull/140).
> [Issue 154] Refactor PMAccuracy testDataTree method

- src/Math-Tests-Accuracy/PMAccuracyTest.class.st
- src/Math-Tests-Accuracy/PMAccuracyTestExample.class.st
In the `issue-154` branch, having configured coverall.io to track the `Accuracy-Core` package, I discovered that `#testExtractFromResultsWhichOnlyOne` was [failing on travisCI](https://travis-ci.org/github/PolyMathOrg/PolyMath/jobs/647741214?utm_medium=notification&utm_source=github_status), specifically, the first of the two assertions.
The name of the test is not very helpful so in this refactoring PR I have broken it up and made the names (hopefully) a little clearer. In addition I've extracted code to role revealing local variables. We can get to the root cause of why it is failing on travisCI in later dev work.
In addition, I introduced a new method, `argumentWith:`, so that we can be explicit about the key we want get the argument for, and replaced calls to `argument` with it. This …
> Issue 154 Refactoring - Make The Test More Specific By Breaking It Up

- .smalltalk.ston
- README.md
- src/Math-Tests-Accuracy/PMAccuracyTestExample.class.st
**Issue:** #154 
This finally puts test coverage on the `Math-Accuracy-Core` package via coveralls.io. Along the way we needed to replace calls to the `argument` message with `argumentWith:`.
> Issue 154 test coverage

- README.md
The badge that links to coveralls.io was pointing to `development`. This PR is to have the link to `master`.
> Corrected the coverage badge so that it points to the master branch.

- src/Math-Tests-Core/PMVectorTest.class.st
I submit this pull request to suggest a test method `PMVectorTest >> testHouseholder`.
We noticed that the method #householder is never executed by any of the tests in PMVectorTest. Therefore we created a test method which uses two vectors to exercise both branches in line 203 `(x <=0) ifTrue: [x -u] ifFalse:  [0 - s / (x + u)]`. In the former vector `x = -1` forces the ifTrue branch in the latter  vector `x = 1.00001` forces the ifFalse branch. 
Note that these suggestions are adapted from a test amplification tool called SmallAmp (https://github.com/mabdi/small-amp). SmallAmp executes existing tests, sees which parts of the class under test are not covered and then suggests improvements on the test methods.
I hope you will accept this pull request. It would illustrate that SmallAmp …
> testHouseholder added

- src/Math-Core/PMVector.class.st
- src/Math-Matrix/PMMatrix.class.st
- src/Math-Tests-Core/PMVectorTest.class.st
- src/Math-Tests-Matrix/PMMatrixTest.class.st
For ``PMMatrix`` and ``PMVector``, which answer the binomial coefficient at each element for a given integer. These are two convenience methods which makes easier to write code using contingency tables (marginals and grand totals).
> Proposed take: implementation

- src/Math-Quantile/SortedCollection.extension.st
- src/Math-Tests-Quantile/PMQuantileTest.class.st
In Pharo 9, in cases like where the input probability is a Float and not a Fraction like
```
#(1 2 3 4 5) asSortedCollection quantile: 0.25
```
an error gets thrown as `SortedCollection` requires an Integer for an index. With the previous code
the value of the temporary value, `p`, could end up being a Float like `2.0` that would equal the integer
( i.e. `p truncate = p` ) but using `2.0` as an index no longer works.
> Fix bug in quantile: where the input probability is given as a float.

- src/Math-Matrix/PMMatrix.class.st
- src/Math-Tests-Matrix/PMMatrixTest.class.st
The `PMMatrix` class did not have the method `atRow:` initialised even though the method `atColumn:` was initialised.
The method, `atRow:` is introduced through this PR.
> add atRow: method for PMMatrix

- src/Math-Matrix/PMMatrix.class.st
- src/Math-Tests-Matrix/PMMatrixTest.class.st
- src/Math-Tests-Matrix/PMSymmetricMatrixTest.class.st
Changes introduced from this PR
- Identity matrix can now be initialized using PMMatrix class
- Added tests for Identity matrix initialization using PMMatrix class
- Added tests for Identity matrix initialization using PMSymmetricMatrix class.
> add identity matrix instance creation for PMMatrix

- src/Math-Matrix/PMMatrix.class.st
- src/Math-Tests-Matrix/PMMatrixTest.class.st
- src/Math-Tests-Numerical/PMNumericalMethodsTestCase.class.st
This PR solves the issue - #205 partially.
Changes introduced with this PR :
- When negative values are given as input to the shapes of a PMMatrix, an AssertionFailure error is returned.
> handle negative values for shapes in PMMatrix

- src/Math-Matrix/PMMatrix.class.st
- src/Math-Tests-Matrix/PMMatrixTest.class.st
Strassen multiplication between two matrices is only possible when the dimensions of both the matrices are a power of 2.
Currently, we get an error when we try to do `strassenProductWithMatrix:` with a matrix of dimension that is not a power of 2.
Changes introduced with this PR:
- An assertion condition is added to the `strassenProductWithMatrix:` method that checks that the shapes of the matrices are a power of 2.
- Unit test to check if the assertion failure is raised when `stassenProductWithMatrix` is called on invalid shapes.
- Unit test that checks if the output of Strassen multiplication on two valid matrices is correct
A better solution for this [problem](https://cs.stackexchange.com/questions/97998/strassens-matrix-multiplication-algorithm-when-n-is-not-a-power-of-2) would be to …
> check for invalid shapes in strassen multiplication

- src/Math-Matrix/PMMatrix.class.st
- src/Math-Tests-Matrix/PMMatrixTest.class.st
A `raisedTo: anInteger` method is added for PMMatrix. Now, exponentiation of matrices can be performed using this method.
Eg: You can calculate A<sup>3</sup> using `A raisedTo: 3`.
> add raisedTo method for PMMatrix

- src/Math-AutomaticDifferenciation/PMDualNumber.class.st
- src/Math-Complex/PMComplex.class.st
- src/Math-Complex/PMComplex.extension.st
- src/Math-Tests-AutomaticDifferenciation/PMDualNumberTest.class.st
- src/Math-Tests-Complex/PMComplexTest.class.st
> Refactor: Introduce complexConjugate Message, Deprecate conjugated

- src/Math-Tests-Complex/PMComplexTest.class.st
Adding some characterisation tests to understand sqrt message so that we have confidence to refactor.
> Complex sqrt characterisation tests

- src/Math-Tests-Complex/PMComplexTest.class.st
As part of issue #192, replaced a long unclear test with specific and clearly named tests for equality.
> Refactor complex number tests: Break up testEquality and Introduce Equivalence Relation Contract and Other Tests

- src/Math-Tests-Complex/PMComplexTest.class.st
- Added a category which emphasises that complex numbers have a polar coordinate form; 
- added missing tests that felt interesting enough to confirm:
--argument of a real number is 0 radians
-- argument of a negative pure imaginary number is - Pi /2 (I was expecting 3 Pi / 2)
> Refactor complex number tests: Categorised the test and added other interesting test cases

- src/Math-Complex/PMComplex.class.st
- src/Math-Complex/PMComplex.extension.st
- src/Math-Tests-Complex/PMComplexTest.class.st
- Categorised the tests that exercise the arithmetic of complex numbers;
- renamed some tests to be a little clearer (inspired by Kevlin Henney's [Structure and Interpretation of Test Cases](https://youtu.be/tWn8RA_DEic))
- added what may be a missing test to demonstrate we cannot take the reciprocal of 0 + 0 i
> Refactor complex number tests: Grouped all arithmetic tests into a clearly named category, added missing interesting test

- src/Math-Complex/Number.extension.st
- src/Math-Complex/PMComplexNumber.class.st
- src/Math-Complex/PMComplexNumber.extension.st
- src/Math-FastFourierTransform/PMFastFourierTransform.class.st
- src/Math-Quaternion/PMComplexNumber.extension.st
- src/Math-Tests-Complex/PMComplexNumberTest.class.st
Issue: #191 
**Breaking Change**
- Renamed the PMComplex class and its Test Case to PMComplexNumber and PMComplexNumberTest respectively;
- migrated clients.
I have chosen to rename the package as a separate PR, as this step has proved difficult.
> Breaking Change: Renamed the class to follow the ubiquitous language.

- src/Math-Tests-Matrix/PMQRTest.class.st
Issue: #279 
I have started by trying to improve clarity in the tests by breaking the test up into well named smaller ones. I hypothesise that it will pin point which scenario is failing.
> Break Up Moore Penrose Test Into Smaller Tests For Clarity and Ease of Debugging

- src/Math-Core/PMVector.class.st
- src/Math-Matrix/PMMatrix.class.st
- src/Math-Matrix/PMQRDecomposition.class.st
- src/Math-Tests-Matrix/PMMatrixTest.class.st
- src/Math-Tests-Matrix/PMQRTest.class.st
This work continues the refactoring, and **has introduced a test that shows why the Moore Penrose Inverse test fails randomly: the pivot of the QR decomposition contains a `nil`**.
I will try to delve deeper into why the pivot has a nil in it at all, and what the answer should be. I will give myself a few days. If I get nowhere, I will make this a full PR ready for review.
> QR Decomposition Method Object Refactoring

- src/Math-Matrix/PMQRDecomposition.class.st
This continues the simplification of the QR Decomposition method object. I have made the idea of the Householder Reflection explicit. I will continue to look more deeply into why the one element of the pivot (last one) is nil.
> Refactor QR Decomposition
